### ISSUE TITLE
poke from ESP8266SDUpdater

### ISSUE THREAD

**Issue by tobozo** [reaper7/ESP8266SPIFFSUpdateFirmware#1]
Just to let you know your project inspired [this](https://github.com/tobozo/ESP8266SDUpdater)

So far I've been able to flash a 700Kb app from the SD card, not sure if this is a lower limit than OTA or SPIFFS updates but still worth sharing 😀

**Comment by reaper7** [comment]
nice to hear :)

BTW
I see that you're using i2c buttons...
I added support for this keyboard to esp8266_deauther
https://github.com/reaper7/esp8266_deauther
works great with wemos d1 mini

**Comment by tobozo** [comment]
Good to know, I've only tested a quick & dirty implementation of the deauther and couldn't have the OLED to work, I'll try your fork tonight ^^

The buttons handling is a bit messy in the original repo code, not really 'other-interfaces' friendly and more focused on Dongsentech builds, so it's not a suprise if similar contributions never ended up in the codebase :-(

Here are two other awesome additions: 

https://github.com/spacehuhn/esp8266_deauther/issues/647
https://github.com/spacehuhn/esp8266_deauther/issues/595

**Comment by reaper7** [comment]
I know, that's why I did not do PR.
I saw a rotary solution but I only have rotary without a button function :)
look on this sandwich:)
https://github.com/reaper7/esp8266_deauther/commit/735d508ec8c62ab3bd568abf382a04a332529cd6#commitcomment-28699154

**Comment by tobozo** [comment]
om nom nom :hamburger: 

I tried to use the X-Pad as a solderless component first (the holes are conveniently disposed for that) with the 64x48 OLED but only managed to break the glass of the screen while trying to reach the buttons, and concluded this little beast has more potential outside the hat if you have clumsy fingers :p

On the picture the I2C pins look very close to the antenna, I'm quite sure this should result in some kind of noise when the OLED or the X-Pad are operating, unless the hot glue helps to minimize this effect?

**Comment by reaper7** [comment]
I use 128x64 display connected by wires to keyboard, the glue just keeps it.
Original oled for wemos (64x48) can not hold all the information (I tried with a smaller font, shortening titles etc).
Keyboard is ~7mm away from the antenna, oled ~11mm

PCBs are connected by just a few bare pins(to minimize distances), 3 pins on the left side (3.3V, GPIO16(pcf int), A0(battery meter))
and 4 pins on the right side (5V (from wemos charger/booster), GND, SDA, SCL)
